name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }] # Update every hour
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata

          plugin_introduction: yes

          plugin_languages: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full_year

          plugin_stars: yes
          plugin_stars_limit: 3

          plugin_repositories: yes

          plugin_activity: yes
